#!/bin/bash

# Test script for Advanced Real Diagram Detection
echo "🔍 Testing Advanced Real Diagram Detection"
echo "========================================"

echo ""
echo "NEW DETECTION METHOD: Advanced PlantUML Diagram Analysis"
echo "- Detects real PlantUML diagrams vs error/setup SVGs"
echo "- Analyzes SVG content for PlantUML-specific elements"
echo "- Filters out empty, error, and setup instruction SVGs"
echo "- Only hides button for actual rendered diagrams"

echo ""
echo "DETECTION CRITERIA:"

echo ""
echo "❌ NOT Real Diagrams (Button should stay VISIBLE):"
echo "- Error messages: 'PlantUML Setup Required', 'Java Required'"
echo "- Empty SVGs: '<!-- No content -->', '<!-- Error: ... -->'"
echo "- Setup instructions and error displays"
echo "- Very small SVGs (< 200 characters)"
echo "- SVGs with no PlantUML-specific elements"

echo ""
echo "✅ Real Diagrams (Button should be HIDDEN):"
echo "- Contains PlantUML elements: <rect>, <path>, <line>, <ellipse>, <polygon>"
echo "- Has PlantUML attributes: class=, stroke=, fill="
echo "- Requires at least 3 PlantUML indicators"
echo "- Substantial SVG content (> 200 characters)"

echo ""
echo "TESTING SCENARIOS:"

echo ""
echo "📝 Test 1: Initial State (No SVG)"
echo "- Expected: Button VISIBLE"
echo "- Console: '[REACTIVE] No SVG element found'"
echo "- Console: '[REACTIVE] ✅ Showing center tutorial button'"

echo ""
echo "📝 Test 2: PlantUML Setup Required"
echo "- Scenario: PlantUML not installed/configured"
echo "- Expected: Button VISIBLE (setup message is not a real diagram)"
echo "- Console: '[REACTIVE] Found error/setup SVG, not a real diagram: PlantUML Setup Required'"
echo "- Console: '[REACTIVE] ✅ Showing center tutorial button'"

echo ""
echo "📝 Test 3: Java Required Error"
echo "- Scenario: Java not installed"
echo "- Expected: Button VISIBLE (error message is not a real diagram)"
echo "- Console: '[REACTIVE] Found error/setup SVG, not a real diagram: Java Required'"
echo "- Console: '[REACTIVE] ✅ Showing center tutorial button'"

echo ""
echo "📝 Test 4: Real Class Diagram"
echo "- Action: Send 'Create a class diagram for User and Order'"
echo "- Expected: Button HIDDEN (real diagram rendered)"
echo "- Console: '[REACTIVE] Diagram analysis: { ..., indicatorCount: 5+, isRealDiagram: true }'"
echo "- Console: '[REACTIVE] ❌ Hiding center tutorial button'"

echo ""
echo "📝 Test 5: Real Sequence Diagram"
echo "- Action: Send 'Create a sequence diagram for login process'"
echo "- Expected: Button HIDDEN (real diagram rendered)"
echo "- Console: '[REACTIVE] Diagram analysis: { ..., indicatorCount: 3+, isRealDiagram: true }'"
echo "- Console: '[REACTIVE] ❌ Hiding center tutorial button'"

echo ""
echo "📝 Test 6: Real Activity Diagram"
echo "- Action: Send 'Create an activity diagram for order processing'"
echo "- Expected: Button HIDDEN (real diagram rendered)"
echo "- Console: '[REACTIVE] Diagram analysis: { ..., indicatorCount: 3+, isRealDiagram: true }'"
echo "- Console: '[REACTIVE] ❌ Hiding center tutorial button'"

echo ""
echo "📝 Test 7: Clear Chat After Real Diagram"
echo "- Action: Click 'Clear Chat' after viewing real diagram"
echo "- Expected: Button VISIBLE (no diagram content)"
echo "- Console: '[REACTIVE] No SVG element found'"
echo "- Console: '[REACTIVE] ✅ Showing center tutorial button'"

echo ""
echo "📝 Test 8: Switch Between Error and Real Diagram"
echo "- Action: View setup error, then render real diagram"
echo "- Expected: Button VISIBLE for error, HIDDEN for real diagram"
echo "- Console: Shows transition from error detection to real diagram detection"

echo ""
echo "DEBUGGING COMMANDS:"
echo "Run these in browser console to debug detection:"

echo ""
echo "1. Check current detection state:"
echo "   const svgPreview = document.getElementById('svgPreview');"
echo "   tutorialButtonState.hasRealDiagram(svgPreview);"

echo ""
echo "2. Analyze current SVG content:"
echo "   const svg = document.querySelector('#svgPreview svg');"
echo "   console.log('SVG content:', svg ? svg.outerHTML : 'No SVG');"

echo ""
echo "3. Check detection details:"
echo "   // Look for '[REACTIVE] Diagram analysis:' in console"
echo "   // Shows indicatorCount, isRealDiagram, and SVG preview"

echo ""
echo "4. Manual state testing:"
echo "   tutorialButtonState.setSvgContent(false);  // Force show button"
echo "   tutorialButtonState.setSvgContent(true);   // Force hide button"

echo ""
echo "5. Check button visibility:"
echo "   const btn = document.getElementById('onboardingBtnCenter');"
echo "   console.log('Button visible:', !btn.classList.contains('hidden'));"

echo ""
echo "EXPECTED CONSOLE OUTPUT EXAMPLES:"

echo ""
echo "✅ For Error/Setup SVGs:"
echo "   [REACTIVE] Found error/setup SVG, not a real diagram: PlantUML Setup Required"
echo "   [REACTIVE] State changed: { ..., hasSvg: false, buttonVisible: true }"
echo "   [REACTIVE] ✅ Showing center tutorial button"

echo ""
echo "✅ For Real Diagrams:"
echo "   [REACTIVE] Diagram analysis: { hasBasicSvg: true, svgLength: 2500, indicatorCount: 6, isRealDiagram: true }"
echo "   [REACTIVE] State changed: { ..., hasSvg: true, buttonVisible: false }"
echo "   [REACTIVE] ❌ Hiding center tutorial button"

echo ""
echo "✅ For Empty State:"
echo "   [REACTIVE] No SVG element found"
echo "   [REACTIVE] State changed: { ..., hasSvg: false, buttonVisible: true }"
echo "   [REACTIVE] ✅ Showing center tutorial button"

echo ""
echo "SUCCESS CRITERIA:"
echo "- Button visible for all error/setup messages"
echo "- Button hidden only for real PlantUML diagrams"
echo "- Console shows detailed analysis of SVG content"
echo "- Proper state transitions between different SVG types"
echo "- No false positives (hiding button for error messages)"
echo "- No false negatives (showing button for real diagrams)"

echo ""
echo "🎯 This advanced detection should solve the button disappearing issue!"
echo "🐛 If button still disappears incorrectly, check console for detection details" 